# Generated by Django 4.2.1 on 2023-06-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catalyst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("domain", models.CharField(max_length=100)),
                ("year_founded", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("locality", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("linked_in_url", models.CharField(max_length=100)),
                ("current_employee_estimate", models.CharField(max_length=100)),
                ("total_employee_estimate", models.CharField(max_length=100)),
            ],
        ),
    ]
