# Generated by Django 4.2.6 on 2023-10-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="post",
            new_name="heading_post",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_heading",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_heading_post",
            field=models.CharField(default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_sub_heading",
            field=models.CharField(default="", max_length=500),
        ),
    ]
