# Generated by Django 4.2.6 on 2023-10-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_auto_20231013_1440"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpdate",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default="")),
                ("update_desc", models.CharField(max_length=5000)),
                ("timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
