# Generated by Django 4.2.6 on 2023-10-21 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                ("profile_img_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "profile_img",
                    models.ImageField(default="profile_icon.png", upload_to=""),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
